<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $currencies = [
            ['id' => 1, 'code' => 'AED', 'name' => 'United Arab Emirates Dirham'],
            ['id' => 2, 'code' => 'AFN', 'name' => 'Afghan Afghani'],
            ['id' => 3, 'code' => 'ALL', 'name' => 'Albanian Lek'],
            ['id' => 4, 'code' => 'AMD', 'name' => 'Armenian Dram'],
            ['id' => 5, 'code' => 'ANG', 'name' => 'Netherlands Antillean Guilder'],
            ['id' => 6, 'code' => 'AOA', 'name' => 'Angolan Kwanza'],
            ['id' => 7, 'code' => 'ARS', 'name' => 'Argentine Peso'],
            ['id' => 8, 'code' => 'AUD', 'name' => 'Australian Dollar'],
            ['id' => 9, 'code' => 'AWG', 'name' => 'Aruban Florin'],
            ['id' => 10, 'code' => 'AZN', 'name' => 'Azerbaijani Manat'],
            ['id' => 11, 'code' => 'BAM', 'name' => 'Bosnia-Herzegovina Convertible Mark'],
            ['id' => 12, 'code' => 'BBD', 'name' => 'Barbadian Dollar'],
            ['id' => 13, 'code' => 'BDT', 'name' => 'Bangladeshi Taka'],
            ['id' => 14, 'code' => 'BGN', 'name' => 'Bulgarian Lev'],
            ['id' => 15, 'code' => 'BHD', 'name' => 'Bahraini Dinar'],
            ['id' => 16, 'code' => 'BIF', 'name' => 'Burundian Franc'],
            ['id' => 17, 'code' => 'BMD', 'name' => 'Bermudan Dollar'],
            ['id' => 18, 'code' => 'BND', 'name' => 'Brunei Dollar'],
            ['id' => 19, 'code' => 'BOB', 'name' => 'Bolivian Boliviano'],
            ['id' => 20, 'code' => 'BRL', 'name' => 'Brazilian Real'],
            ['id' => 21, 'code' => 'BSD', 'name' => 'Bahamian Dollar'],
            ['id' => 22, 'code' => 'BTC', 'name' => 'Bitcoin'],
            ['id' => 23, 'code' => 'BTN', 'name' => 'Bhutanese Ngultrum'],
            ['id' => 24, 'code' => 'BWP', 'name' => 'Botswanan Pula'],
            ['id' => 25, 'code' => 'BYN', 'name' => 'Belarusian Ruble'],
            ['id' => 26, 'code' => 'BYR', 'name' => 'Belarusian Ruble (pre-2016)'],
            ['id' => 27, 'code' => 'BZD', 'name' => 'Belize Dollar'],
            ['id' => 28, 'code' => 'CAD', 'name' => 'Canadian Dollar'],
            ['id' => 29, 'code' => 'CDF', 'name' => 'Congolese Franc'],
            ['id' => 30, 'code' => 'CHF', 'name' => 'Swiss Franc'],
            ['id' => 31, 'code' => 'CLF', 'name' => 'Chilean Unit of Account (UF)'],
            ['id' => 32, 'code' => 'CLP', 'name' => 'Chilean Peso'],
            ['id' => 33, 'code' => 'CNY', 'name' => 'Chinese Yuan'],
            ['id' => 34, 'code' => 'COP', 'name' => 'Colombian Peso'],
            ['id' => 35, 'code' => 'CRC', 'name' => 'Costa Rican Colón'],
            ['id' => 36, 'code' => 'CUC', 'name' => 'Cuban Convertible Peso'],
            ['id' => 37, 'code' => 'CUP', 'name' => 'Cuban Peso'],
            ['id' => 38, 'code' => 'CVE', 'name' => 'Cape Verdean Escudo'],
            ['id' => 39, 'code' => 'CZK', 'name' => 'Czech Koruna'],
            ['id' => 40, 'code' => 'DJF', 'name' => 'Djiboutian Franc'],
            ['id' => 41, 'code' => 'DKK', 'name' => 'Danish Krone'],
            ['id' => 42, 'code' => 'DOP', 'name' => 'Dominican Peso'],
            ['id' => 43, 'code' => 'DZD', 'name' => 'Algerian Dinar'],
            ['id' => 44, 'code' => 'EGP', 'name' => 'Egyptian Pound'],
            ['id' => 45, 'code' => 'ERN', 'name' => 'Eritrean Nakfa'],
            ['id' => 46, 'code' => 'ETB', 'name' => 'Ethiopian Birr'],
            ['id' => 47, 'code' => 'EUR', 'name' => 'Euro'],
            ['id' => 48, 'code' => 'FJD', 'name' => 'Fijian Dollar'],
            ['id' => 49, 'code' => 'FKP', 'name' => 'Falkland Islands Pound'],
            ['id' => 50, 'code' => 'GBP', 'name' => 'British Pound Sterling'],
            ['id' => 51, 'code' => 'GEL', 'name' => 'Georgian Lari'],
            ['id' => 52, 'code' => 'GGP', 'name' => 'Guernsey Pound'],
            ['id' => 53, 'code' => 'GHS', 'name' => 'Ghanaian Cedi'],
            ['id' => 54, 'code' => 'GIP', 'name' => 'Gibraltar Pound'],
            ['id' => 55, 'code' => 'GMD', 'name' => 'Gambian Dalasi'],
            ['id' => 56, 'code' => 'GNF', 'name' => 'Guinean Franc'],
            ['id' => 57, 'code' => 'GTQ', 'name' => 'Guatemalan Quetzal'],
            ['id' => 58, 'code' => 'GYD', 'name' => 'Guyanaese Dollar'],
            ['id' => 59, 'code' => 'HKD', 'name' => 'Hong Kong Dollar'],
            ['id' => 60, 'code' => 'HNL', 'name' => 'Honduran Lempira'],
            ['id' => 61, 'code' => 'HRK', 'name' => 'Croatian Kuna'],
            ['id' => 62, 'code' => 'HTG', 'name' => 'Haitian Gourde'],
            ['id' => 63, 'code' => 'HUF', 'name' => 'Hungarian Forint'],
            ['id' => 64, 'code' => 'IDR', 'name' => 'Indonesian Rupiah'],
            ['id' => 65, 'code' => 'ILS', 'name' => 'Israeli New Sheqel'],
            ['id' => 66, 'code' => 'IMP', 'name' => 'Manx pound'],
            ['id' => 67, 'code' => 'INR', 'name' => 'Indian Rupee'],
            ['id' => 68, 'code' => 'IQD', 'name' => 'Iraqi Dinar'],
            ['id' => 69, 'code' => 'IRR', 'name' => 'Iranian Rial'],
            ['id' => 70, 'code' => 'ISK', 'name' => 'Icelandic Króna'],
            ['id' => 71, 'code' => 'JEP', 'name' => 'Jersey Pound'],
            ['id' => 72, 'code' => 'JMD', 'name' => 'Jamaican Dollar'],
            ['id' => 73, 'code' => 'JOD', 'name' => 'Jordanian Dinar'],
            ['id' => 74, 'code' => 'JPY', 'name' => 'Japanese Yen'],
            ['id' => 75, 'code' => 'KES', 'name' => 'Kenyan Shilling'],
            ['id' => 76, 'code' => 'KGS', 'name' => 'Kyrgyzstani Som'],
            ['id' => 77, 'code' => 'KHR', 'name' => 'Cambodian Riel'],
            ['id' => 78, 'code' => 'KMF', 'name' => 'Comorian Franc'],
            ['id' => 79, 'code' => 'KPW', 'name' => 'North Korean Won'],
            ['id' => 80, 'code' => 'KRW', 'name' => 'South Korean Won'],
            ['id' => 81, 'code' => 'KWD', 'name' => 'Kuwaiti Dinar'],
            ['id' => 82, 'code' => 'KYD', 'name' => 'Cayman Islands Dollar'],
            ['id' => 83, 'code' => 'KZT', 'name' => 'Kazakhstani Tenge'],
            ['id' => 84, 'code' => 'LAK', 'name' => 'Laotian Kip'],
            ['id' => 85, 'code' => 'LBP', 'name' => 'Lebanese Pound'],
            ['id' => 86, 'code' => 'LKR', 'name' => 'Sri Lankan Rupee'],
            ['id' => 87, 'code' => 'LRD', 'name' => 'Liberian Dollar'],
            ['id' => 88, 'code' => 'LSL', 'name' => 'Lesotho Loti'],
            ['id' => 89, 'code' => 'LTL', 'name' => 'Lithuanian Litas'],
            ['id' => 90, 'code' => 'LVL', 'name' => 'Latvian Lats'],
            ['id' => 91, 'code' => 'LYD', 'name' => 'Libyan Dinar'],
            ['id' => 92, 'code' => 'MAD', 'name' => 'Moroccan Dirham'],
            ['id' => 93, 'code' => 'MDL', 'name' => 'Moldovan Leu'],
            ['id' => 94, 'code' => 'MGA', 'name' => 'Malagasy Ariary'],
            ['id' => 95, 'code' => 'MKD', 'name' => 'Macedonian Denar'],
            ['id' => 96, 'code' => 'MMK', 'name' => 'Myanmar Kyat'],
            ['id' => 97, 'code' => 'MNT', 'name' => 'Mongolian Tugrik'],
            ['id' => 98, 'code' => 'MOP', 'name' => 'Macanese Pataca'],
            ['id' => 99, 'code' => 'MRO', 'name' => 'Mauritanian Ouguiya'],
            ['id' => 100, 'code' => 'MUR', 'name' => 'Mauritian Rupee'],
            ['id' => 101, 'code' => 'MVR', 'name' => 'Maldivian Rufiyaa'],
            ['id' => 102, 'code' => 'MWK', 'name' => 'Malawian Kwacha'],
            ['id' => 103, 'code' => 'MXN', 'name' => 'Mexican Peso'],
            ['id' => 104, 'code' => 'MYR', 'name' => 'Malaysian Ringgit'],
            ['id' => 105, 'code' => 'MZN', 'name' => 'Mozambican Metical'],
            ['id' => 106, 'code' => 'NAD', 'name' => 'Namibian Dollar'],
            ['id' => 107, 'code' => 'NGN', 'name' => 'Nigerian Naira'],
            ['id' => 108, 'code' => 'NIO', 'name' => 'Nicaraguan Córdoba'],
            ['id' => 109, 'code' => 'NOK', 'name' => 'Norwegian Krone'],
            ['id' => 110, 'code' => 'NPR', 'name' => 'Nepalese Rupee'],
            ['id' => 111, 'code' => 'NZD', 'name' => 'New Zealand Dollar'],
            ['id' => 112, 'code' => 'OMR', 'name' => 'Omani Rial'],
            ['id' => 113, 'code' => 'PAB', 'name' => 'Panamanian Balboa'],
            ['id' => 114, 'code' => 'PEN', 'name' => 'Peruvian Sol'],
            ['id' => 115, 'code' => 'PGK', 'name' => 'Papua New Guinean Kina'],
            ['id' => 116, 'code' => 'PHP', 'name' => 'Philippine Peso'],
            ['id' => 117, 'code' => 'PKR', 'name' => 'Pakistani Rupee'],
            ['id' => 118, 'code' => 'PLN', 'name' => 'Polish Złoty'],
            ['id' => 119, 'code' => 'PYG', 'name' => 'Paraguayan Guarani'],
            ['id' => 120, 'code' => 'QAR', 'name' => 'Qatari Riyal'],
            ['id' => 121, 'code' => 'RON', 'name' => 'Romanian Leu'],
            ['id' => 122, 'code' => 'RSD', 'name' => 'Serbian Dinar'],
            ['id' => 123, 'code' => 'RUB', 'name' => 'Russian Ruble'],
            ['id' => 124, 'code' => 'RWF', 'name' => 'Rwandan Franc'],
            ['id' => 125, 'code' => 'SAR', 'name' => 'Saudi Riyal'],
            ['id' => 126, 'code' => 'SBD', 'name' => 'Solomon Islands Dollar'],
            ['id' => 127, 'code' => 'SCR', 'name' => 'Seychellois Rupee'],
            ['id' => 128, 'code' => 'SDG', 'name' => 'Sudanese Pound'],
            ['id' => 129, 'code' => 'SEK', 'name' => 'Swedish Krona'],
            ['id' => 130, 'code' => 'SGD', 'name' => 'Singapore Dollar'],
            ['id' => 131, 'code' => 'SHP', 'name' => 'Saint Helena Pound'],
            ['id' => 132, 'code' => 'SLL', 'name' => 'Sierra Leonean Leone'],
            ['id' => 133, 'code' => 'SOS', 'name' => 'Somali Shilling'],
            ['id' => 134, 'code' => 'SRD', 'name' => 'Surinamese Dollar'],
            ['id' => 135, 'code' => 'SSP', 'name' => 'South Sudanese Pound'],
            ['id' => 136, 'code' => 'STD', 'name' => 'São Tomé and Príncipe Dobra'],
            ['id' => 137, 'code' => 'SVC', 'name' => 'Salvadoran Colón'],
            ['id' => 138, 'code' => 'SYP', 'name' => 'Syrian Pound'],
            ['id' => 139, 'code' => 'SZL', 'name' => 'Swazi Lilangeni'],
            ['id' => 140, 'code' => 'THB', 'name' => 'Thai Baht'],
            ['id' => 141, 'code' => 'TJS', 'name' => 'Tajikistani Somoni'],
            ['id' => 142, 'code' => 'TMT', 'name' => 'Turkmenistani Manat'],
            ['id' => 143, 'code' => 'TND', 'name' => 'Tunisian Dinar'],
            ['id' => 144, 'code' => 'TOP', 'name' => 'Tongan Paʻanga'],
            ['id' => 145, 'code' => 'TRY', 'name' => 'Turkish Lira'],
            ['id' => 146, 'code' => 'TTD', 'name' => 'Trinidad and Tobago Dollar'],
            ['id' => 147, 'code' => 'TWD', 'name' => 'New Taiwan Dollar'],
            ['id' => 148, 'code' => 'TZS', 'name' => 'Tanzanian Shilling'],
            ['id' => 149, 'code' => 'UAH', 'name' => 'Ukrainian Hryvnia'],
            ['id' => 150, 'code' => 'UGX', 'name' => 'Ugandan Shilling'],
            ['id' => 151, 'code' => 'USD', 'name' => 'United States Dollar'],
            ['id' => 152, 'code' => 'UYU', 'name' => 'Uruguayan Peso'],
            ['id' => 153, 'code' => 'UZS', 'name' => 'Uzbekistan Som'],
            ['id' => 154, 'code' => 'VEF', 'name' => 'Venezuelan Bolívar'],
            ['id' => 155, 'code' => 'VND', 'name' => 'Vietnamese Đồng'],
            ['id' => 156, 'code' => 'VUV', 'name' => 'Vanuatu Vatu'],
            ['id' => 157, 'code' => 'WST', 'name' => 'Samoan Tālā'],
            ['id' => 158, 'code' => 'XAF', 'name' => 'Central African CFA Franc'],
            ['id' => 159, 'code' => 'XCD', 'name' => 'East Caribbean Dollar'],
            ['id' => 160, 'code' => 'XDR', 'name' => 'Special Drawing Rights'],
            ['id' => 161, 'code' => 'XOF', 'name' => 'West African CFA Franc'],
            ['id' => 162, 'code' => 'XPF', 'name' => 'CFP Franc'],
            ['id' => 163, 'code' => 'YER', 'name' => 'Yemeni Rial'],
            ['id' => 164, 'code' => 'ZAR', 'name' => 'South African Rand'],
            ['id' => 165, 'code' => 'ZMW', 'name' => 'Zambian Kwacha'],
            ['id' => 166, 'code' => 'ZWL', 'name' => 'Zimbabwean Dollar'],
        ];
        // DB::table('currencies')->insert($currencies);
        Currency::insert($currencies);
    }
}